[package]
name = "ccurl"
version = "0.3.0"
authors = ["OmarAouini <aouini.omar93@gmail.com>"]
edition = "2018"

[dependencies]
ureq = {version = "2.1.1", features = ["json", "charset"] }
json-color = "0.7.1"